//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.7-1.2.0.0_2-1-7-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.08 at 06:20:54 PM PDT 
//


package com.oracle.cep.siebel.jaxb.event;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.oracle.cep.siebel.jaxb.event package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ActivitiesOutput_QNAME = new QName("http://xmlns.oracle.com/ns/healthcare", "ActivitiesOutput");
    private final static QName _ActivitiesInput_QNAME = new QName("http://xmlns.oracle.com/ns/healthcare", "ActivitiesInput");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.oracle.cep.siebel.jaxb.event
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ActivitiesInputType }
     * 
     */
    public ActivitiesInputType createActivitiesInputType() {
        return new ActivitiesInputType();
    }

    /**
     * Create an instance of {@link ActivitiesOutputType }
     * 
     */
    public ActivitiesOutputType createActivitiesOutputType() {
        return new ActivitiesOutputType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivitiesOutputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/ns/healthcare", name = "ActivitiesOutput")
    public JAXBElement<ActivitiesOutputType> createActivitiesOutput(ActivitiesOutputType value) {
        return new JAXBElement<ActivitiesOutputType>(_ActivitiesOutput_QNAME, ActivitiesOutputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivitiesInputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/ns/healthcare", name = "ActivitiesInput")
    public JAXBElement<ActivitiesInputType> createActivitiesInput(ActivitiesInputType value) {
        return new JAXBElement<ActivitiesInputType>(_ActivitiesInput_QNAME, ActivitiesInputType.class, null, value);
    }

}
